### ISSUE TITLE
get_matrix() function takes around 0.5 second ?! It is an issue for online control.

### ISSUE THREAD

**Issue by LyuJZ** [UM-ARM-Lab/pytorch_kinematics#24]
Hi, thanks a lot for sharing this useful package with the community. I am using it for robot online control now. However, I found `get_matrix()` function takes some time to get the result. Is there any chance to solve this issue?

**Comment by LemonPi** [comment]
The transform operations are lazily evaluated, so when `get_matrix()` takes a long time, it is likely due to it being the result of chaining a number of operations. Before retrieving the matrix, can you take a look at what operations are chained? It could be that there is a lot of unnecessary operations there.

**Comment by PeterMitrano** [comment]
@LyuJZ we've just merged some changes that improve the performance. Check it out!
